Filters: Add blocker filters
mavlink-router/mavlink-router pull request #402
Opened 2023-08-05 19:49 UTC by OhadNir9

Like the filters that allow messages with specific parameters (msg_id, sys_id and comp_id) to pass as outgoing/incoming messages in/to endpoints, the new filters enabling blockage of messages with such parameters.
This feature co-exists with the current "allow" filters, with the only exception that a message that appears in both filter types (allow and block) will eventually be **blocked**.

Unit-tested, but not yet tested in real setup.

2023-08-07 11:22 UTC, jbeyerstedt requested changes
Sorry to be quite nit-picky about the formatting, but it helps keeping the code in a readable and maintainable state. In general the code seems fine though.

But could you please add some sentence to the readme, that it doesn't make any sense to specify an "allow" and a "block" filter for the same identifier type. But mixing e.g. a message ID block list with a system ID allow list is fine.

2023-08-07 11:22 UTC, jbeyerstedt commented on src/endpoint.cpp
> +
Again: Why the extra newline? There already was one to separate the two "blocks" of for each loops.

2023-08-07 11:22 UTC, jbeyerstedt commented on src/endpoint.cpp
> +    }
And why was the newline before `this->_group_name ...` removed?

2023-08-07 11:22 UTC, jbeyerstedt commented on src/endpoint.h
> +
Again: Why extra newline?

2023-08-07 11:22 UTC, jbeyerstedt commented on README.md
> +    be sent via this endpoint
Lines should be max. 80 characters wide, so the `be sent` shall still be on the first line.

2023-08-07 11:25 UTC, jbeyerstedt commented
Out of curiosity (and reasoning why to add more features): What's your use case for this? (I only had use for explicit allow lists when implementing the full set of filters.)

2023-08-07 11:26 UTC, jbeyerstedt commented on src/endpoint.h
> +
clang-format has the same question by the way

2023-08-07 11:27 UTC, jbeyerstedt commented on src/endpoint.cpp
> +
clang-format has the same question by the way

2023-08-07 11:40 UTC, OhadNir9 commented
Sorry for the formatting issues..I'll fix them soon.
My use case was MissionPlanner - appearently every time it starts up, it sends right away a REQUEST_DATA_STREAM message with some specific rates, that conflicts with the IMU data message rates I needed for another algorithm. I looked for an easy way to block this REQUEST_DATA_STREAM messages from coming out the MP endpoint

2023-08-10 17:24 UTC, OhadNir9 commented
Seems like the CI is broken? @jbeyerstedt

2023-08-28 14:18 UTC, jbeyerstedt commented
> Seems like the CI is broken? @jbeyerstedt

Please rebase, CI should be fixed now.

2023-09-06 08:17 UTC, jbeyerstedt commented
The Readme section about message filters got quite long now, so I would propose to rework it like in the attached patch file:[0001-Readme-Rework-message-filter-section.patch](https://github.com/mavlink-router/mavlink-router/files/12535080/0001-Readme-Rework-message-filter-section.patch)

(I can't push to your branch, so this was the quickest solution which came to my mind. Just try to "git apply" it to your branch.)

2023-09-17 12:38 UTC, OhadNir9 commented
Hi, I've applied the requested changes @jbeyerstedt

2023-09-18 08:36 UTC, jbeyerstedt commented
Squashed and merged manually

2023-09-18 08:36 UTC, closed without merging